### ISSUE TITLE
Proposal: Deprecate view-layer "owner" for 1.11

### ISSUE THREAD

**Issue by dcporter** [sproutcore/sproutcore#1254]
The view-layer concept of "owner" has been nothing more than a synonym for parentView for a while. I would like to deprecate it for 1.11 by replacing it in SC.CoreView with a calculated property that throws a developer warning and returns parentView.

I'm interested in making a move on this for 1.11 because I would very much like to claim `owner` for another concept – giving a complex view class's childViews access to the root class view without having to count parentViews.

Thoughts?

**Comment by publickeating** [comment]
I believe that the reason `owner` exists is for that exact concept, but nothing really takes advantage of it. Even `SC.CollectionView` items, which have their `owner` set to the collection view end up such that their `parentView` just so happens to be the same view.

I think it's feasible for a view to assign `owner` more than one level deep, so I'm leaning towards documenting `owner` along the lines of "This is the view responsible for managing this view as a child… it may or may not be the direct parentView". Then again, does an owner have to be a direct ancestor of another view? And at what level does "ownership" begin? Couldn't it just as well be some object or controller? Which seems like an overlap with the purpose of delegates. 

Finally, what do we expect a view to use `owner` for? I surmise it's primarily to bind backwards up to properties set on ancestor views, which might be better accomplished by using controller singletons instead.

Yeah, it seems pretty useless. Deprecating...

**Comment by dcporter** [comment]
Well for example I recently ran across a comment in my first-ever SproutCore project expressing exasperation that my list view was secretly *two* parentViews away from its scroll view. Making the scroll view owner of the list view would bypass this confusing point.

I make no representation that this is a fully-baked idea, but my concept for this was simply to allow views to specify isOwner, and for the owner property to run up the parentView hierarchy until it found an owner view. A developer could set isOwner at the top of their complex view class, and have easy access to the top from the tip. (Until she dropped a ScrollView somewhere in the class, at which point things within the scroll view would have to do `this.getPath('owner.owner')` – and now we're back to counting things, and in a much less clear way.)

**Comment by publickeating** [comment]
I see. Well, it's moving aside now: https://github.com/sproutcore/sproutcore/commit/5b9e541c708d020375d5b1fd6646c026042bf41e

**Comment by dcporter** [comment]
:+1:
