### ISSUE TITLE
SC.MenuPane is broken when items overflow

### ISSUE THREAD

**Issue by nicolasbadia** [sproutcore/sproutcore#1283]
If items overflow the window, the heigh of SC.MenuPane is incorrect, which lead to a pane not being scrollable.

**Comment by nicolasbadia** [comment]
This is still an issue for me.

**Comment by nicolasbadia** [comment]
Here is a branch which fixes issues I had with `SC.MenuPane` and `SC.MenuScrollView`: https://github.com/sproutcore/sproutcore/compare/team/nicolasbadia/menu-scroll-fixes

I'm not sure it is the best way to solve them (especially the `SC.MenuPane` part), but it may be useful to someone until a proper fix is pushed.

**Comment by publickeating** [comment]
I’ve gone through the changes and only one of them I disagreed with slightly (I believe the adjust hash width & height needs to be set even if a transition isn’t used in SC.MenuPane, see my commit: https://github.com/sproutcore/sproutcore/commit/445f33a584bfe936315dfda7c5985a55c4562254 <https://github.com/sproutcore/sproutcore/commit/445f33a584bfe936315dfda7c5985a55c4562254>).

I’ve pushed all the changes to master, please test them out if you can I’d like to release 1.11.0 final this week. Thanks @nicolasbadia

--
Tyler Keating
tyler@sproutcore.com

**Comment by publickeating** [comment]
All good?

**Comment by nicolasbadia** [comment]
Yes all good.
