### ISSUE TITLE
SelectView Overflow Doesn't Scroll

### ISSUE THREAD

**Issue by jribar** [sproutcore/sproutcore#1313]
When there is a large number of items in the SelectView list that exceeds what can be displayed on the screen, the list extends off of the screen rather then scrolling.

As a possibly related issue, the second SelectView in the "Disabled" section of the Showcase app (http://showcase.sproutcore.com/#ui/SC.SelectView) doesn't render its menu in the correct position.  Verified with Safari, FF and Chrome on OS 10.10.

**Comment by jribar** [comment]
It appears this may be related to a similar issue (#1283) involving SC.MenuPane.

**Comment by nicolasbadia** [comment]
Indeed, looks like the same issue.

**Comment by publickeating** [comment]
Thanks for bringing this to our attention. I believe it's all been fixed on master now. Showcase will need to be rebuilt and redeployed still.

**Comment by publickeating** [comment]
Just redeployed Showcase.
