### ISSUE TITLE
SC.ScrollView not responding after an item of a collection as been drag

### ISSUE THREAD

**Issue by nicolasbadia** [sproutcore/sproutcore#1331]
When dragging an item of a collection, the `mouseUp` event is not call, and so `_sc_isMouseDown` is not reset to false.

**Comment by mauritslamers** [comment]
Could this perhaps have to do with a recent change in SC.Event, as mentioned here: https://github.com/sproutcore/rich-text-editor/pull/27 ?

**Comment by nicolasbadia** [comment]
Cannot reproduce anymore...
