### ISSUE TITLE
Strange rose lignes in Retina Display

### ISSUE THREAD

**Issue by contrerasmarc** [sproutcore/sproutcore#1335]
Hi

I found strange rose lines when I display my projects in My Retina Display MacBook Pro !
![screen shot 2015-03-02 at 14 07 47](https://cloud.githubusercontent.com/assets/592301/6483353/3b813f2c-c270-11e4-807a-385ade6527b6.png)

When I display it in my normal LCD monitor everything going on well.
![screen shot 2015-03-02 at 14 09 44](https://cloud.githubusercontent.com/assets/592301/6483356/41e5d1f2-c270-11e4-8d40-4308f80da182.png)
![screen shot 2015-03-02 at 14 09 44]

Marcos

**Comment by publickeating** [comment]
Those images are lacking retina versions, I'm going to make some right now (it'll take me a little while to do though)

**Comment by publickeating** [comment]
I've created retina versions for SC.ButtonView and SC.ToolbarView, plus I created additional theme sizes for capsule and pointer buttons (including retina versions). 

Pushed to master branch.
