### ISSUE TITLE
A little fault in the Guide: SproutCore Records

### ISSUE THREAD

**Issue by contrerasmarc** [sproutcore/sproutcore#1344]
Hi

At point 4.1.1 - Creating Associated Records, the example shows two cases. I suppose the second one must be: 
contact.set('address').pushObject(address);

Regards
Marcos

**Comment by mauritslamers** [comment]
No, this is not an error. 

The original line is: 

```contact.get('address').pushObject(address);```

You have to realize that the property address sort of works like a computed property (a RecordAttribute to be exact), which act like a translator to the underlying plain javascript value.
In case of a ManyArray, you first have to get a reference to the RecordArray which contains the nested records, before you can push a new address onto it.

Using set in this context would replace the record attribute / record array, which is not what you want.

Moreover, your code would set the address property to undefined (as you didn't provide a value to set), so this line would cause an error like "Uncaught TypeError: Cannot read property 'pushObject' of undefined".
