### ISSUE TITLE
Remove the use of SC.keyFor()

### ISSUE THREAD

**Issue by mauritslamers** [sproutcore/sproutcore#1348]
SC.keyFor is a function in the runtime framework which is used to cache strings, particularly strings used for KVO in the Observable mixin. (code @ https://github.com/sproutcore/sproutcore/blob/master/frameworks/runtime/core.js#L408)

The issue with SC.keyFor is that it is documented as a more efficient solution to simply adding strings by using +. While it might have been true once, it is no longer the case. Simple speed tests show that SC.keyFor is around 80 times slower than simply adding strings.

```
var test = function(f, times) {
  var start = new Date().getTime();
  for (var i = 0; i < times; i += 1) {
    f();
  }
  return new Date().getTime() - start;
}

test(function () { var t= "test"; return SC.keyFor("this is a ", t); }, 10000000);
> 1684
test(function () { var t= "test"; return "this is a " + t; }, 10000000);
> 21

```

Replacing the SC.keyFor function by a simple returning the plussed string: 

```
SC.keyFor = function (prefix, key) { return prefix + "_" + key; }

test(function () { var t= "test"; return SC.keyFor("this is a ", t); }, 10000000);
> 1433
```

Replacing the SC.keyFor function by defining a global SC.KEYSEP and using that instead:

```
SC.KEYSEP = "_";
test(function () { var t= "test"; return "this is a " + SC.KEYSEP + t; }, 10000000);
> 1395
test(function () { var t= "test"; return "this is a " + "_" + t; }, 10000000);
> 12
```

While the use of SC.keyFor forces a strict style in how these (often) private names are created, not doing this through a function call or not having to look up anything allows a speedup in the KVO part of SC.
Whatever advantage it might bring by not triggering the GC seems to be not worth the trouble.

**Comment by nicolasbadia** [comment]
Agree to remove it.

**Comment by nicolasbadia** [comment]
Closing this as `SC.keyFor` has been deprecated. Just added a comment in order not to forget to remove it in the future.
