### ISSUE TITLE
Remove workaround in SC.routes for fixed Firefox bug

### ISSUE THREAD

**Issue by alleyj** [sproutcore/sproutcore#1356]
In the hashChange function in SC.routes there is a "workaround" for an old Firefox bug, https://bugzilla.mozilla.org/show_bug.cgi?id=483304, where location.hash would return already decoded. This bug has been fixed by Firefox so the "workaround" should be removed.

In older versions of Firefox calling decodeURI on an already decoded value won't cause any problems. And in newer versions of Firefox, at least in our case, not calling decodeURI would spam append garbage to the URL.

**Comment by nicolasbadia** [comment]
Thanks for the report. I just published a PR to fix that.
