### ISSUE TITLE
Make SC.ArrayController accept paths for orderBy

### ISSUE THREAD

**Issue by mauritslamers** [sproutcore/sproutcore#1415]
Currently orderBy does not allow property paths for orderBy.

https://github.com/sproutcore/sproutcore/blob/master/frameworks/core_foundation/controllers/array.js#L412

By changing the a.get call into a.getPath (also for the next line), orderBy also works for propertyPaths. This makes sorting also work with nested records.

**Comment by nicolasbadia** [comment]
Fixed by https://github.com/sproutcore/sproutcore/commit/e67fe3c351780ef3c22753c4cd95a29bcb50298f
