### ISSUE TITLE
SC.TextFieldView does not hide hint when applyImmediately is false

### ISSUE THREAD

**Issue by mauritslamers** [sproutcore/sproutcore#1417]
When a SC.TextFieldView is used, applyImmediately is set to false and the hint is displayed through an overlay (which is the default), the hint is not hidden.

This can be fixed by adding an else clause to the `_textField_inputDidChange` function:

https://github.com/sproutcore/sproutcore/blob/master/frameworks/foundation/views/text_field.js#L992

```
  _textField_inputDidChange: function () {
    var timerNotPending = SC.empty(this._fieldValueDidChangeTimer) || !this._fieldValueDidChangeTimer.get('isValid');
    if (this.get('applyImmediately') && timerNotPending) {
      this.invokeLater(this.fieldValueDidChange, 10);
    }
    else {
      this.updateHintOnFocus();
    }
  },
```

**Comment by nicolasbadia** [comment]
Fixed by https://github.com/sproutcore/sproutcore/commit/30cd08e15033bad6a1288cf80b005ab57513aeb8
