### ISSUE TITLE
Inconstancies with no/multiple selection API on Collection Views

### ISSUE THREAD

**Issue by jribar** [sproutcore/sproutcore#173]
CollectionView is expecting to find allowsMultipleSelection set on the content object (which assumes that SelectionSupport is mixed in) rather then as a property on the CollectionView itself.

However ColectionView ignores the allowsEmptySelection property from the SelectionSupport mixin.  This feature is available by setting the completely undocumented allowDeselectAll property on the CollectionView.

This API should be cleaned up so that for collections where you can select 0 or more items, you do not have to define one property on the content object/controller and the other on the CollectionView.

**Comment by nicolasbadia** [comment]
I believe this two commits https://github.com/sproutcore/sproutcore/pull/1443/commits/3f563bc9845f913cb30f41ade058aa0c792210c8 and https://github.com/sproutcore/sproutcore/pull/1443/commits/2fcf3c428bcfd31a2d36e13557c2ccf9beb477a6 solve this issue.
They define `allowsEmptySelection` and `allowsMultipleSelection` as computed properties on SC.Collection. This way, if you don't want to set theses properties on the delegate/content, you can directly override them on the collection.
