### ISSUE TITLE
Test template should be configurable

### ISSUE THREAD

**Issue by jamesarosen** [sproutcore/sproutcore#246]
[Gregory Moeck's jasmine-sproutcore](https://github.com/gmoeck/jasmine-sproutcore) is a nearly perfect drop-in replacement for QUnit in Sproutcore. It suffers from one problem, though: `sc create` still generates a QUnit test. The plugin does offer a separate Jasmine spec generator, but it would be really nice if it could hook into the SC generation system instead.

**Comment by mauritslamers** [comment]
Because this is essentially related to abbot (the ruby buildtools) and we are moving away from it, I will close this issue. Supporting multiple test frameworks is a nice idea though, so I will make an issue on the new buildtools.
