### ISSUE TITLE
The class names are not cleanup anymore when the view is update

### ISSUE THREAD

**Issue by nicolasbadia** [sproutcore/sproutcore#984]
To see the problem in action, simply setup a list view with showAlternatingRows to true. After having scroll up and down, the class 'odd' and 'even' are present on every item.

**Comment by PenguinMan98** [comment]
I've just gotten a task to correct this problem in our app.  Is there any resolution?

**Comment by PenguinMan98** [comment]
Working with Mauritslamers, we were able to correct this issue by adding the property 'isReusable: false' to the exampleView View class.

**Comment by mauritslamers** [comment]
It turns out that when you are using a custom exampleView which does not extend from SC.ListItemView, you might need to add 

```isReusable: false```

if you have the same issue as described above.
